In [1]:
import tensorflow as tf

In [2]:
w = [[1,2,3],[4,5,6],[7,8,9]]
x = [[1],[2],[3]]

W = tf.Variable(w, "int32")
X = tf.Variable(x, "int32")


y = tf.matmul(W,x)
print (y)

Tensor("MatMul:0", shape=(3, 1), dtype=int32)


In [3]:
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    result = sess.run(y)
print (result)

[[14]
 [32]
 [50]]


In [4]:
w = [[1,2,3],[4,5,6],[7,8,9]]
x0 = [[1],[2],[3]]
x1 = [[0],[0],[0]]
x2 = [[1],[1],[1]]
vectors =[x0,x1,x2]

W = tf.Variable(w, "int32")
x_ph = tf.placeholder("int32", [3,1])

y2 = tf.matmul(W, x_ph)

result_list = []
with tf.Session() as sess2:
    sess2.run(tf.initialize_all_variables())
    for v in vectors:
        result_list.append(sess2.run(y2,feed_dict={x_ph: v}))

print ("{},{},{}".format(*result_list))

[[14]
 [32]
 [50]],[[0]
 [0]
 [0]],[[ 6]
 [15]
 [24]]


### 学習内容 ###
- ねこ　ー＞　にゃーん
- いぬ　ー＞　わんわん
- うさぎ　ー＞　・・・。

を学習させる。


In [56]:
cat = [[1.],[0.],[0.]]
dog = [[0.],[1.],[0.]]
rabbit= [[0.],[0.],[1.]]

nyan =  [[1.],[0.],[0.]]
wan =  [[0.],[1.],[0.]]
silent = [[0.],[0.],[1.]]

data_set = [(cat,nyan)]*500 +[(dog,wan)]*500+[(rabbit, silent)]*500
data_set
import random
random.shuffle(data_set)

In [57]:
w = [[0.,0.,0.],[0.,0.,0.],[0.,0.,0.]]
W = tf.Variable(w, "float")
x = tf.placeholder(tf.float32, [3,1])
y = tf.matmul(W,x)
y_ = tf.placeholder(tf.float32, [3,1])

cost = tf.reduce_sum(tf.pow(y - y_, 2))

train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cost)


with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    for i in range(len(data_set)):
        sess.run(train_step, feed_dict={x: data_set[i][0], y_: data_set[i][1]})
        if i % 100 == 0:
            error = sess.run(cost,feed_dict={x: data_set[i][0], y_: data_set[i][1]})
            print ("{}回目のエラー関数の値: {}".format(i,error))
    w_result = sess.run(W)

print(w_result)

0回目のエラー関数の値: 0.9604000449180603
100回目のエラー関数の値: 0.22424866259098053
200回目のエラー関数の値: 0.06154582276940346
300回目のエラー関数の値: 0.0190682765096426
400回目のエラー関数の値: 0.0041066971607506275
500回目のエラー関数の値: 0.0013248182367533445
600回目のエラー関数の値: 0.00024274192401207983
700回目のエラー関数の値: 7.222939893836156e-05
800回目のエラー関数の値: 1.619712566025555e-05
900回目のエラー関数の値: 5.440040240500821e-06
1000回目のエラー関数の値: 1.0804467365232995e-06
1100回目のエラー関数の値: 3.7785940776302596e-07
1200回目のエラー関数の値: 9.960752578308529e-08
1300回目のエラー関数の値: 2.0583176052468843e-08
1400回目のエラー関数の値: 7.2041075327433646e-09
[[ 0.99995899  0.          0.        ]
 [ 0.          0.99995899  0.        ]
 [ 0.          0.          0.99995899]]
